ROOT/ROOT/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from character import urls as characters_urls
from achievements import urls as achievement_urls
from game import urls as game_urls

import achievements.views
import character.views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', character.views.index, name="index"),
    url(r'^c/', include(characters_urls, namespace="character")),
    url(r'^a/', include(achievement_urls)),
    # url(r'^g/', include(game_urls)),
    url(r'^embed/', achievements.views.embed),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ROOT/character/urls.py
from . import views
from django.conf.urls import url

urlpatterns = [

    url(r'^overview/$', views.overview, name='overview'),
    url(r'^places/$', views.places, name='places'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),

]

ROOT/character/models.py
from django.contrib.auth.models import User
from django.db import models

class Character(models.Model):

    def __str__(self):
        return "{}: {}".format(self.user.id, self.user.username)

    user = models.OneToOneField(
        'auth.user',
    )

    image = models.ImageField(
        blank=True, null=True,
    )

    XP = models.PositiveIntegerField(
        default=0,
    )
    points = models.PositiveIntegerField(
        default=0,
    )
    level = models.PositiveIntegerField(
        default=0,
    )
    # optional location
    lon = models.FloatField(
        blank=True, null=True,
    )
    lat = models.FloatField(
        blank=True, null=True,
    )

ROOT/character/views.py
from achievements.models import Achievement
from character.models import Character
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.contrib import auth # login, logout, authenticate
from django.contrib.auth.forms import AuthenticationForm

# Create your views here.
from django.template import loader, RequestContext
from achievements.models import AchievementUnlocked


def index(request):
    if not request.user.is_authenticated():
            return HttpResponseRedirect(reverse("character:login"))

    return render(request, "index.html", {
        'character': Character.objects.get(user=request.user)
    })

def overview(request):

    template = loader.get_template("recent_achievements.html")
    achievements = list()
    for a in AchievementUnlocked.objects.filter(character__user=request.user, unlocked__isnull=False).order_by('-unlocked')[:5]:
        item = {
            'image_url': a.achievement.icon.url if a.achievement.icon else '',
            'achievement_description': a.achievement.description,
            'achievement_name': a.achievement.name,
            'unlock_date': a.unlocked
        }
        achievements.append(item)

    context = RequestContext(request, {
        'achievements': achievements
    })
    achievement_tab = template.render(context)
    #

    template = loader.get_template("all_achievements.html")
    achievements = list()
    no_users = Character.objects.all().count()
    for a in Achievement.objects.all():
        total_unlocked = AchievementUnlocked.objects.filter(achievement=a).count()
        item = {
            'image_url': a.icon.url if a.icon else '',
            'achievement_description': a.description,
            'achievement_name': a.name,
            'achievement_unlocked_total': total_unlocked,
            'users_total': no_users,
        }
        au = AchievementUnlocked.objects.filter(achievement=a, character__user=request.user)
        if au:
            au = au[0]
            if au.unlocked is not None:
                item['is_unlocked'] = True
                item['unlock_date'] = au.unlocked
        achievements.append(item)
    context = RequestContext(request, {
        'achievements': achievements
    })
    achievement_all = template.render(context)
    return render(request, "overview.html", {
        'achievement_tab': achievement_tab,
        'achievement_all': achievement_all
    })

def login(request):
    form = AuthenticationForm(request)
    message = ""
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                auth.login(request, user)
                # Redirect to a success page.
                return HttpResponseRedirect(reverse("index"))
            else:
                message = "disabled account"
        else:
            message = "invalid login"
    return render(request, "login.html", {"error_msg": message, "form":form})

def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse("index"))

def places(request):
    return render(request, "places.html")

ROOT/character/templates/index.html
{% extends "base.html" %}
{% load staticfiles %}

{% block extra_head %}
  <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.3/leaflet.css" />
{% endblock %}

{% block bodyel %}
class="fill"
{% endblock %}

{% block body %}
    <div class="container-fluid">
      <div id="header-row" class="row">
        <span class="title">Caracas</span>
        {% if user.is_authenticated %}
          <span><a id="logout" href="{% url 'character:logout' %}"> Logout </a></span>
        {% else %}
          <!-- <a href="login">Log in</a> -->
        {% endif %}
        <span id="settings"> <span class="glyphicon glyphicon-cog" aria-hidden="true"></span> </span>
<!--           <span id="search-box" class="input-group">
             <input type="text" class="form-control" placeholder="Search for...">
             <span class="input-group-btn">
                <button class="btn btn-default glyphicon glyphicon-search" type="button">
                </button>
             </span>
          </span>
-->
        <span id="search-box"> <input type="text" placeholder="Search"><button class="btn btn-default glyphicon glyphicon-search" type="button"></button> </span>
      </div>
      <div id="avatar">

          <div id="charsheet">
              <div id="username">{{ character.user.username }} (Level {{ character.level }}) {{ character.XP }} XP</div>
              <div id="userimage"><img src="{{ character.image.url }}"></div>
              <a onclick="javascript:$('#avatar').animate({'height': '450px'}, 100);" href="#">&#x25BC;</a>
          </div>
          
          <div class="buttons">
              <button class="btn" onclick="javascript:window.loadCharacterBar('{% url 'character:overview' %}')">Achievements</button>
              <button class="btn" onclick="javascript:window.loadCharacterBar('{% url 'character:places' %}')">Places</button>
              <button class="btn">Quests</button>
              <button class="btn">Knowledge</button>
          </div>

      </div>
      <div id="dumping-ground"></div>
      <div class="row">
      </div>
    </div>
    <div id="map"></div>


{% endblock %}

{% block after_body %}
  <script src="http://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.3/leaflet.js"></script>
  <script type="text/javascript" src="http://maps.stamen.com/js/tile.stamen.js?v1.3.0"></script>
  <script type="text/javascript">
    var map = L.map('map').setView([{{ latitude | default:"51.2457"}}, {{ longitude | default:"6.7681"}}], 15);
    // L.tileLayer('//{s}.tile.osm.org/{z}/{x}/{y}.png', {
    L.tileLayer('//stamen-tiles-{s}.a.ssl.fastly.net/watercolor/{z}/{x}/{y}.png', {
        maxZoom: 18
    }).addTo(map);
  </script>
  <script type="text/javascript" src="{% static "map.js" %}"></script>
{% endblock %}

ROOT/character/templates/login.html
{% extends "base.html" %}
{% load staticfiles %}

{% block extra_head %}
  <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.3/leaflet.css" />
{% endblock %}

{% block bodyel %}
class="fill"
{% endblock %}

{% block body %}
<div class="title">Caracas</div>
<div id="login-container"></div>
<div id="login">
    {% if form.errors %}
        <p>Your username and password didn't match. Please try again.</p>
    {% endif %}

    <form method="post" action="">
        {% csrf_token %}
        {{ form.as_p }}

        <input type="submit" value="login" />
        <input type="hidden" name="next" value="{{ next }}" />
        <p>{{ message }}</p>
    </form>
</div>
<div id="map" style="height: 100%;"></div>
    <style>.leaflet-control-container { display: none; }</style>

{% endblock %}

{% block after_body %}
  <script src="http://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.3/leaflet.js"></script>
  <script type="text/javascript" src="http://maps.stamen.com/js/tile.stamen.js?v1.3.0"></script>
  <script type="text/javascript">
    var map = L.map('map').setView([{{ latitude | default:"51.2457"}}, {{ longitude | default:"6.7681"}}], 15);
    // L.tileLayer('//{s}.tile.osm.org/{z}/{x}/{y}.png', {
    L.tileLayer('//stamen-tiles-{s}.a.ssl.fastly.net/watercolor/{z}/{x}/{y}.png', {
        maxZoom: 18
    }).addTo(map);
  </script>
  <script type="text/javascript" src="{% static "map.js" %}"></script>
{% endblock %}

ROOT/character/templates/overview.html
<ul class="nav nav-tabs" id="myTab">
    <li><a onclick="$(this).tab('show');" href="#unlocked">unlocked recently</a></li>
    <li><a onclick="$(this).tab('show');" href="#achievements">all Achievements</a></li>
</ul>

<div class="tab-content">
    <div class="tab-pane" id="unlocked">
        {{ achievement_tab | safe }}
    </div>
    <div class="tab-pane" id="achievements">
        {{ achievement_all | safe }}
    </div>
</div>

<script>
    $('#myTab a:first').tab('show');
</script>

ROOT/character/templates/places.html
{% load staticfiles %}
<ul class="nav nav-tabs" id="myTab">
    <li><a onclick="$(this).tab('show');" href="#visited">Visited</a></li>
    <li><a onclick="$(this).tab('show');" href="#planned">Planned</a></li>
</ul>

<div class="tab-content">
    <div class="tab-pane" id="visited" style="overflow:hidden">
        <div class="achievement_item">

        <figure style="display:inline-block;">
            <img class="unlocked" src="{% static "empty.png" %}" alt="Paris"/>
            <figcaption>
              Paris
            </figcaption>
          </figure>
          <div class="achievement_unlocked_date">unlocked at September 12th 1979</div>
        </div>
        <hr>
        <div class="achievement_item">

        <figure>
            <img class="unlocked" src="{% static "empty.png" %}" alt="Mount Everest"/>
            <figcaption>
              Mount Everest
            </figcaption>
          </figure>
          <div class="achievement_unlocked_date">unlocked at June 26th 2016</div>
        </div>
        <hr>

        <div class="achievement_item">

        <figure>
            <img class="unlocked" src="{% static "empty.png" %}" alt="Greenland"/>
            <figcaption>
              Greenland
            </figcaption>
          </figure>
          <div class="achievement_unlocked_date">unlocked at January 1st 1970</div>
        </div>
        <hr>

        <div class="achievement_item">

        <figure>
            <img class="unlocked" src="{% static "empty.png" %}" alt="Gelsenkirchen"/>
            <figcaption>
              Gelsenkirchen
            </figcaption>
          </figure>
          <div class="achievement_unlocked_date">unlocked at February 14th 2012</div>
        </div>
        <hr>



    </div>
    <div class="tab-pane" id="planned">

    </div>
</div>

<script>
    $('#myTab a:first').tab('show');
</script>